export const CATEGORIES = [
  "Kerja",
  "Belajar",
  "Personal",
  "Kesehatan",
  "Kebersihan / Rumah",
  "Proyek",
  "Hiburan",
  "Olahraga",
  "Kreativitas",
  "Finance / Keuangan",
];

export const SUBCATEGORIES: Record<string, string[]> = {
  Kerja: [
    "Emails",
    "Meetings",
    "Planning",
    "Reporting",
    "Coding / Development",
    "UI/UX Design",
    "Customer Support",
    "Content Writing",
    "Editing / Reviewing",
    "Marketing Tasks",
    "Project Management",
    "Data Entry",
    "Research",
    "Administrative Work",
  ],
  Belajar: [
    "Mathematics",
    "Science",
    "History",
    "Languages",
    "Economics",
    "Programming",
    "Exam Preparation",
    "Reading",
    "Research",
    "School Assignments",
    "Online Courses",
    "Skill Improvement",
  ],
  Personal: [
    "Journaling",
    "Meditation",
    "Rest",
    "Reflection",
    "Time Management",
    "Family Time",
    "Self Improvement",
    "Personal Goals",
  ],
  Kesehatan: [
    "Stretching",
    "Medical Check",
    "Therapy",
    "Mental Health",
    "Meal Planning",
    "Breathing Exercise",
    "Water Intake",
  ],
  "Kebersihan / Rumah": [
    "Cleaning Room",
    "Laundry",
    "Washing Dishes",
    "Organizing Items",
    "Groceries",
    "Taking Out Trash",
    "Cooking",
    "Tidying Desk",
  ],
  Proyek: [
    "Research Project",
    "Writing Project",
    "Coding Project",
    "Design Project",
    "Long-Term Goals",
    "Assignment Project",
    "Event Preparation",
  ],
  Hiburan: [
    "Watching Movies",
    "Watching Series",
    "Gaming",
    "Music",
    "Reading Novels",
    "Hobbies",
    "Social Media",
  ],
  Olahraga: [
    "Running",
    "Walking",
    "Cycling",
    "Gym Workout",
    "Yoga",
    "Sports Training",
    "Home Workout",
  ],
  Kreativitas: [
    "Drawing",
    "Writing",
    "Music Production",
    "Crafting",
    "Photography",
    "Video Editing",
    "Graphic Design",
  ],
  "Finance / Keuangan": [
    "Budgeting",
    "Expense Tracking",
    "Learning Finance",
    "Planning Purchases",
    "Paying Bills",
    "Financial Review",
  ],
};
